ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE;
ALTER TABLE favorite_lots ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE;
ALTER TABLE favorite_contractors ADD COLUMN IF NOT EXISTS archived BOOLEAN DEFAULT FALSE;